# -*- coding: utf-8 -*-
"""travel_planner.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H3idyvLvwDz9uehroCUw5NUfQp9-LKf1
"""

"""
╔══════════════════════════════════════════════════════════════╗
   GRAPH-BASED TRAVEL PLANNER SYSTEM  v3.0
   Advanced DSA Project

   NEW in v3.0:
     ★ Tourist Attractions per city (with visit time & cost)
     ★ Fuel Cost Estimator (petrol / diesel / EV)
     ★ Safety Rating per route
     ★ Best Season to Travel advisory
     ★ Trip Summary Report (distance + cost + fuel + attractions)
     ★ Multi-stop / Waypoint routing
     ★ Nearest city finder

   Core DSA: Dijkstra · BFS · DFS · Stack · Queue ·
             Priority Queue · Adjacency List
   Extra:    Roadblocks · Weather-based routing
╚══════════════════════════════════════════════════════════════╝
"""

import heapq
import math
import random
from collections import deque, defaultdict


# ════════════════════════════════════════════════════════════════
#  STACK
# ════════════════════════════════════════════════════════════════
class Stack:
    """Array-backed Stack — O(1) push / pop."""
    def __init__(self):            self._d = []
    def push(self, x):             self._d.append(x)
    def pop(self):
        if self.is_empty(): raise IndexError("Stack underflow")
        return self._d.pop()
    def peek(self):
        if self.is_empty(): raise IndexError("Stack empty")
        return self._d[-1]
    def is_empty(self):            return not self._d
    def size(self):                return len(self._d)
    def __repr__(self):            return f"Stack({self._d})"


# ════════════════════════════════════════════════════════════════
#  QUEUE
# ════════════════════════════════════════════════════════════════
class Queue:
    """Deque-backed Queue — O(1) enqueue / dequeue."""
    def __init__(self):            self._d = deque()
    def enqueue(self, x):          self._d.append(x)
    def dequeue(self):
        if self.is_empty(): raise IndexError("Queue underflow")
        return self._d.popleft()
    def front(self):               return self._d[0]
    def is_empty(self):            return not self._d
    def size(self):                return len(self._d)
    def __repr__(self):            return f"Queue({list(self._d)})"


# ════════════════════════════════════════════════════════════════
#  PRIORITY QUEUE  (min-heap — Dijkstra)
# ════════════════════════════════════════════════════════════════
class PriorityQueue:
    def __init__(self):            self._h = []
    def push(self, pri, item):     heapq.heappush(self._h, (pri, item))
    def pop(self):                 return heapq.heappop(self._h)
    def is_empty(self):            return not self._h


# ════════════════════════════════════════════════════════════════
#  WEATHER
# ════════════════════════════════════════════════════════════════
WEATHER_CONDITIONS = ["Clear", "Cloudy", "Rainy", "Foggy", "Stormy", "Snowy"]
WEATHER_MULT = {"Clear":1.0,"Cloudy":1.1,"Rainy":1.3,"Foggy":1.5,"Stormy":2.0,"Snowy":1.8}
WEATHER_ADV  = {
    "Clear":  "✅ Perfect conditions.",
    "Cloudy": "🌥  Mild — drive normally.",
    "Rainy":  "🌧  Wet roads — reduce speed.",
    "Foggy":  "🌫  Low visibility — fog lights on.",
    "Stormy": "⛈  Severe — avoid if possible!",
    "Snowy":  "❄️  Icy roads — use snow chains.",
}
WEATHER_ICON = {"Clear":"☀️","Cloudy":"🌥","Rainy":"🌧","Foggy":"🌫","Stormy":"⛈","Snowy":"❄️"}

BEST_SEASON = {
    "Delhi":     "Oct–Mar  (avoid May–Jul heat)",
    "Mumbai":    "Nov–Feb  (avoid Jun–Sep monsoon)",
    "Bangalore": "Sep–Feb  (pleasant year-round)",
    "Chennai":   "Nov–Feb  (avoid Oct–Dec cyclone season)",
    "Hyderabad": "Oct–Feb  (avoid Apr–Jun heat)",
    "Kolkata":   "Oct–Feb  (avoid Jun–Sep monsoon)",
    "Pune":      "Oct–Feb  (avoid Jun–Aug heavy rain)",
    "Jaipur":    "Oct–Mar  (avoid Apr–Jun desert heat)",
}

class WeatherSystem:
    def __init__(self, seed=42):
        random.seed(seed)
        self._m: dict[tuple,str] = {}

    def set_weather(self, a, b, cond):
        if cond not in WEATHER_CONDITIONS:
            raise ValueError(f"Unknown: {cond}")
        self._m[tuple(sorted([a,b]))] = cond

    def get_weather(self, a, b) -> str:
        k = tuple(sorted([a,b]))
        if k not in self._m:
            self._m[k] = random.choice(WEATHER_CONDITIONS)
        return self._m[k]

    def get_mult(self, a, b) -> float:
        return WEATHER_MULT[self.get_weather(a,b)]


# ════════════════════════════════════════════════════════════════
#  ROADBLOCKS
# ════════════════════════════════════════════════════════════════
class RoadblockSystem:
    def __init__(self):
        self._bl: set[tuple]  = set()
        self._rs: dict[tuple,str] = {}

    def add(self, a, b, reason="Under maintenance"):
        k = tuple(sorted([a,b]))
        self._bl.add(k); self._rs[k] = reason

    def remove(self, a, b):
        k = tuple(sorted([a,b]))
        self._bl.discard(k); self._rs.pop(k, None)

    def blocked(self, a, b) -> bool:
        return tuple(sorted([a,b])) in self._bl

    def reason(self, a, b) -> str:
        return self._rs.get(tuple(sorted([a,b])), "Unknown")

    def all(self) -> list[tuple]:
        return list(self._bl)


# ════════════════════════════════════════════════════════════════
#  ★ TOURIST ATTRACTIONS  (NEW)
# ════════════════════════════════════════════════════════════════
# Each attraction: (name, visit_time_hr, entry_cost_inr, category, description)
ATTRACTIONS: dict[str, list[tuple]] = {
    "Delhi": [
        ("Red Fort",           2.0,  35,   "Heritage",  "Iconic Mughal fort on the Yamuna river"),
        ("Qutub Minar",        1.5,  40,   "Heritage",  "UNESCO World Heritage minaret complex"),
        ("India Gate",         1.0,   0,   "Monument",  "War memorial in the heart of New Delhi"),
        ("Lotus Temple",       1.0,   0,   "Religious", "Stunning Bahá'í House of Worship"),
        ("Chandni Chowk",      2.0,   0,   "Market",    "Oldest and busiest market in Old Delhi"),
    ],
    "Mumbai": [
        ("Gateway of India",   1.0,   0,   "Monument",  "Iconic arch overlooking the Arabian Sea"),
        ("Marine Drive",       1.5,   0,   "Scenic",    "Queen's Necklace — stunning sea promenade"),
        ("Elephanta Caves",    3.0, 600,   "Heritage",  "UNESCO rock-cut cave temples on an island"),
        ("Dharavi",            2.0, 750,   "Cultural",  "Asia's largest informal settlement — guided tour"),
        ("Siddhivinayak Temple",1.0,  0,   "Religious", "Famous Ganesha temple, great spiritual energy"),
    ],
    "Bangalore": [
        ("Lalbagh Botanical Garden", 2.0, 20, "Nature", "200-year-old garden with rare plant species"),
        ("Cubbon Park",              1.5,  0, "Nature",  "Green lungs of Bangalore — 300 acres"),
        ("Bangalore Palace",         1.5, 230,"Heritage","Tudor-style palace inspired by Windsor Castle"),
        ("ISKCON Temple",            1.0,  0, "Religious","Gorgeous Krishna temple complex"),
        ("UB City Mall",             1.5,  0, "Shopping", "Luxury shopping destination"),
    ],
    "Chennai": [
        ("Marina Beach",         2.0,  0,   "Scenic",   "World's longest natural urban beach"),
        ("Kapaleeshwarar Temple",1.5,  0,   "Religious","Ancient Dravidian-style Shiva temple"),
        ("Fort St. George",      1.5, 15,   "Heritage", "First English fortress in India — now a museum"),
        ("Mahabalipuram",        4.0, 40,   "Heritage", "UNESCO shore temples & rock carvings (day trip)"),
        ("Arignar Anna Zoo",     3.0, 60,   "Nature",   "One of the largest zoological parks in India"),
    ],
    "Hyderabad": [
        ("Charminar",            1.5, 25,   "Heritage", "400-year-old mosque & iconic city symbol"),
        ("Golconda Fort",        3.0, 25,   "Heritage", "Majestic medieval fort with incredible acoustics"),
        ("Ramoji Film City",     6.0, 1500, "Entertainment","World's largest film studio — full day experience"),
        ("Hussain Sagar Lake",   1.5,  0,   "Scenic",   "Stunning heart-shaped lake with Buddha statue"),
        ("Salar Jung Museum",    2.5, 20,   "Culture",  "One of India's largest one-man collection museums"),
        ("Birla Mandir",         1.0,  0,   "Religious","Beautiful white marble temple atop a rocky hill"),
    ],
    "Kolkata": [
        ("Victoria Memorial",    2.0, 30,   "Heritage", "Magnificent marble monument to Queen Victoria"),
        ("Howrah Bridge",        1.0,  0,   "Monument", "Iconic cantilever bridge over the Hooghly"),
        ("Dakshineswar Temple",  1.5,  0,   "Religious","Famous Kali temple on the Hooghly river"),
        ("Indian Museum",        2.5, 20,   "Culture",  "Oldest & largest museum in India"),
        ("Park Street",          1.5,  0,   "Market",   "The city's most iconic food & shopping street"),
    ],
    "Pune": [
        ("Shaniwar Wada",        1.5, 25,   "Heritage", "18th-century fortification of Peshwa rulers"),
        ("Aga Khan Palace",      1.5, 25,   "Heritage", "Historic palace where Gandhi was imprisoned"),
        ("Sinhagad Fort",        3.0, 50,   "Adventure","Trek to this historic hilltop fort — great views"),
        ("Osho Ashram",          2.0,  0,   "Spiritual","International meditation resort"),
        ("Koregaon Park",        1.5,  0,   "Scenic",   "Trendy upscale neighbourhood with cafes & art"),
    ],
    "Jaipur": [
        ("Amber Fort",           3.0, 500,  "Heritage", "Magnificent hilltop fort with mirror palace"),
        ("Hawa Mahal",           1.0, 200,  "Heritage", "Palace of Winds — stunning pink sandstone facade"),
        ("City Palace",          2.0, 700,  "Heritage", "Royal residence with museums & courtyards"),
        ("Jantar Mantar",        1.5, 200,  "Heritage", "UNESCO astronomical observatory — 18th century"),
        ("Johari Bazaar",        1.5,   0,  "Market",   "Famous for gemstones, jewellery & Rajasthani craft"),
    ],
}


def display_attractions(city: str, budget_filter: float | None = None):
    """Print tourist attractions for a city, optionally filtered by budget."""
    spots = ATTRACTIONS.get(city, [])
    if not spots:
        print(f"  No attraction data for {city}.")
        return

    print(f"\n  🏛️   Tourist Attractions in {city}")
    print("  " + "─" * 70)
    print(f"  {'#':<3} {'Attraction':<28} {'Time':>6}  {'Entry':>8}  {'Type':<14}  Notes")
    print("  " + "─" * 70)

    total_time = total_cost = 0.0
    shown = 0
    for i, (name, t, c, cat, desc) in enumerate(spots, 1):
        if budget_filter is not None and c > budget_filter:
            continue
        shown += 1
        total_time += t
        total_cost += c
        cost_str = f"Rs {c}" if c > 0 else "FREE"
        print(f"  {i:<3} {name:<28} {t:>4.1f}h  {cost_str:>8}  {cat:<14}  {desc[:35]}")

    print("  " + "─" * 70)
    print(f"  {'TOTAL':<31} {total_time:>4.1f}h  Rs {total_cost:>6.0f}")
    if budget_filter is not None and shown == 0:
        print(f"  (No attractions under Rs {budget_filter:.0f} budget)")


def attractions_on_route(path: list[str]) -> dict[str, list]:
    """Return attractions dict for every city on a path."""
    return {city: ATTRACTIONS.get(city, []) for city in path}


def route_attraction_summary(path: list[str]):
    """Print a summary of all attractions along a route."""
    print(f"\n  🗺️   Attraction Summary Along Route")
    print("  " + "═" * 65)
    grand_time = grand_cost = 0.0
    for city in path:
        spots = ATTRACTIONS.get(city, [])
        if not spots:
            continue
        city_time = sum(s[1] for s in spots)
        city_cost = sum(s[2] for s in spots)
        grand_time += city_time
        grand_cost += city_cost
        print(f"\n  📍 {city}  ({len(spots)} spots | {city_time:.1f}h | Rs {city_cost:.0f})")
        for name, t, c, cat, _ in spots:
            cost_str = f"Rs {c}" if c > 0 else "FREE"
            icon = {"Heritage":"🏛️","Religious":"🕌","Monument":"🗿","Scenic":"🌅",
                    "Nature":"🌿","Culture":"🎭","Market":"🛍️","Shopping":"🛍️",
                    "Adventure":"⛰️","Entertainment":"🎬","Spiritual":"🧘","Cultural":"🎨"}.get(cat,"📌")
            print(f"     {icon} {name:<26} {t:.1f}h  {cost_str}")
    print(f"\n  ─── Grand Total ───────────────────────────────────────")
    print(f"  ⏱️   Total visit time : {grand_time:.1f} h  ({grand_time/8:.1f} day(s))")
    print(f"  💰  Total entry cost  : Rs {grand_cost:.0f}")
    print("  " + "═" * 65)


# ════════════════════════════════════════════════════════════════
#  ★ FUEL COST ESTIMATOR  (NEW)
# ════════════════════════════════════════════════════════════════
FUEL_RATES = {
    "Petrol":  {"price_per_litre": 104.0, "kmpl": 15.0},
    "Diesel":  {"price_per_litre":  92.0, "kmpl": 20.0},
    "CNG":     {"price_per_kg":     84.0, "km_per_kg": 25.0},
    "EV":      {"price_per_kwh":     8.0, "km_per_kwh": 6.5},
}

def fuel_cost(distance_km: float, vehicle: str = "Petrol") -> float:
    v = FUEL_RATES.get(vehicle, FUEL_RATES["Petrol"])
    if vehicle == "Petrol":
        return (distance_km / v["kmpl"]) * v["price_per_litre"]
    elif vehicle == "Diesel":
        return (distance_km / v["kmpl"]) * v["price_per_litre"]
    elif vehicle == "CNG":
        return (distance_km / v["km_per_kg"]) * v["price_per_kg"]
    elif vehicle == "EV":
        return (distance_km / v["km_per_kwh"]) * v["price_per_kwh"]
    return 0.0

def fuel_comparison(distance_km: float):
    print(f"\n  ⛽  Fuel Cost Comparison  ({distance_km:.0f} km)")
    print("  " + "─" * 45)
    print(f"  {'Vehicle':<12} {'Fuel Cost':>12}  Details")
    print("  " + "─" * 45)
    for v, info in FUEL_RATES.items():
        cost = fuel_cost(distance_km, v)
        if v in ("Petrol", "Diesel"):
            detail = f"{distance_km/info['kmpl']:.1f} L @ Rs {info['price_per_litre']}/L"
        elif v == "CNG":
            detail = f"{distance_km/info['km_per_kg']:.1f} kg @ Rs {info['price_per_kg']}/kg"
        else:
            detail = f"{distance_km/info['km_per_kwh']:.1f} kWh @ Rs {info['price_per_kwh']}/kWh"
        print(f"  {v:<12} Rs {cost:>8.2f}   {detail}")
    print("  " + "─" * 45)


# ════════════════════════════════════════════════════════════════
#  ★ SAFETY RATING  (NEW)
# ════════════════════════════════════════════════════════════════
# (city_a, city_b) -> safety score 1–10 (10 = safest)
SAFETY_RATINGS: dict[tuple, int] = {
    ("Delhi",    "Jaipur"):    7,
    ("Delhi",    "Mumbai"):    8,
    ("Delhi",    "Kolkata"):   7,
    ("Mumbai",   "Pune"):      9,
    ("Mumbai",   "Bangalore"): 8,
    ("Mumbai",   "Hyderabad"): 7,
    ("Bangalore","Chennai"):   9,
    ("Bangalore","Hyderabad"): 8,
    ("Chennai",  "Hyderabad"): 6,
    ("Hyderabad","Kolkata"):   7,
    ("Pune",     "Hyderabad"): 8,
    ("Jaipur",   "Mumbai"):    7,
}

def get_safety(a: str, b: str) -> int:
    k  = tuple(sorted([a, b]))
    k2 = (a, b)
    return SAFETY_RATINGS.get(k, SAFETY_RATINGS.get(k2, 7))

def safety_label(score: int) -> str:
    if score >= 9: return "🟢 Very Safe"
    if score >= 7: return "🟡 Safe"
    if score >= 5: return "🟠 Moderate"
    return "🔴 Caution"


# ════════════════════════════════════════════════════════════════
#  TRAVEL GRAPH
# ════════════════════════════════════════════════════════════════
class TravelGraph:
    """
    Weighted undirected graph (Adjacency List).
    Edge: (neighbor, distance_km, cost_inr, time_hr)
    """
    def __init__(self):
        self.adj: dict[str, list] = defaultdict(list)
        self.cities: set[str] = set()
        self.weather   = WeatherSystem()
        self.roadblocks = RoadblockSystem()
        self.history   = Stack()          # route history

    # ── Construction ────────────────────────
    def add_route(self, a, b, dist, cost, time):
        for c in (a, b): self.cities.add(c)
        self.adj[a].append((b, dist, cost, time))
        self.adj[b].append((a, dist, cost, time))

    def get_all_edges(self):
        seen, edges = set(), []
        for city, nbrs in self.adj.items():
            for nb, *_ in nbrs:
                k = tuple(sorted([city, nb]))
                if k not in seen:
                    seen.add(k); edges.append(k)
        return edges

    # ── Dijkstra ────────────────────────────
    def dijkstra(self, src, tgt, weight="distance", weather=False):
        widx = {"distance":0,"cost":1,"time":2}[weight]
        dist = {c: math.inf for c in self.cities}
        prev = {c: None    for c in self.cities}
        dist[src] = 0
        pq = PriorityQueue(); pq.push(0, src)

        while not pq.is_empty():
            d, u = pq.pop()
            if d > dist[u]: continue
            for nb, *ws in self.adj[u]:
                if self.roadblocks.blocked(u, nb): continue
                w = ws[widx]
                if weather: w *= self.weather.get_mult(u, nb)
                alt = dist[u] + w
                if alt < dist[nb]:
                    dist[nb] = alt; prev[nb] = u
                    pq.push(alt, nb)

        path, node = [], tgt
        while node: path.append(node); node = prev[node]
        path.reverse()
        if not path or path[0] != src: return math.inf, []
        return dist[tgt], path

    # ── BFS ─────────────────────────────────
    def bfs(self, src) -> list:
        visited, order = {src}, []
        q = Queue(); q.enqueue(src)
        while not q.is_empty():
            c = q.dequeue(); order.append(c)
            for nb, *_ in sorted(self.adj[c], key=lambda x: x[0]):
                if nb not in visited and not self.roadblocks.blocked(c, nb):
                    visited.add(nb); q.enqueue(nb)
        return order

    # ── DFS ─────────────────────────────────
    def dfs(self, src, visited=None) -> list:
        if visited is None: visited = set()
        visited.add(src); order = [src]
        for nb, *_ in sorted(self.adj[src], key=lambda x: x[0]):
            if nb not in visited and not self.roadblocks.blocked(src, nb):
                order.extend(self.dfs(nb, visited))
        return order

    # ── All Paths ───────────────────────────
    def all_paths(self, src, tgt, path=None) -> list:
        if path is None: path = [src]
        if src == tgt: return [path[:]]
        res = []
        for nb, *_ in self.adj[src]:
            if nb not in path and not self.roadblocks.blocked(src, nb):
                path.append(nb)
                res.extend(self.all_paths(nb, tgt, path))
                path.pop()
        return res

    # ── Nearest City ─────────────────────────
    def nearest_cities(self, src: str, n: int = 3) -> list:
        """Return n nearest cities by distance from src."""
        results = []
        for tgt in self.cities:
            if tgt == src: continue
            total, path = self.dijkstra(src, tgt, "distance")
            if path: results.append((total, tgt))
        results.sort()
        return results[:n]

    # ── Multi-stop route ─────────────────────
    def multi_stop_route(self, waypoints: list[str], weight="distance"):
        """Chain Dijkstra across multiple waypoints."""
        full_path, grand_total = [], 0.0
        for i in range(len(waypoints) - 1):
            total, path = self.dijkstra(waypoints[i], waypoints[i+1], weight)
            if not path:
                return math.inf, []
            grand_total += total
            full_path.extend(path if i == 0 else path[1:])
        return grand_total, full_path

    # ── History helpers ──────────────────────
    def push_history(self, entry): self.history.push(entry)
    def undo_last(self):
        if self.history.is_empty():
            print("  Nothing to undo."); return None
        return self.history.pop()


# ════════════════════════════════════════════════════════════════
#  DISPLAY HELPERS
# ════════════════════════════════════════════════════════════════
W = 68

def banner(text):
    print("\n" + "█" * W)
    pad = max(0, (W - len(text)) // 2)
    print(" " * pad + text)
    print("█" * W)

def section(title):
    print("\n╔" + "═" * (W - 2) + "╗")
    print(f"  ▶  {title}")
    print("╚" + "═" * (W - 2) + "╝")

def div():
    print("  " + "─" * (W - 4))


# ════════════════════════════════════════════════════════════════
#  ★ FULL ANALYSIS  (upgraded)
# ════════════════════════════════════════════════════════════════
def full_analysis(g: TravelGraph, source: str, target: str, vehicle: str = "Petrol"):
    banner(f"TRAVEL ANALYSIS  :  {source}  →  {target}")
    UNITS = {"distance":"km","cost":"Rs","time":"h"}
    ICONS = {"distance":"📏","cost":"💰","time":"⏱️"}
    results = {}

    # ─── 1. Dijkstra (3 weights) ──────────────
    section("1.  Shortest Paths — Dijkstra's Algorithm")
    for w in ["distance","cost","time"]:
        tot, path = g.dijkstra(source, target, w)
        results[w] = (tot, path)
        if path:
            print(f"\n  {ICONS[w]}  Optimised by {w.upper()}:")
            print(f"      Value   : {tot:.2f} {UNITS[w]}")
            print(f"      Route   : {' → '.join(path)}")
            print(f"      Hops    : {len(path)-1} segment(s)")
        else:
            print(f"\n  {ICONS[w]}  {w.upper()}: ❌ No path (roadblocks may be cutting route)")
        g.push_history({"type":"dijkstra","source":source,"target":target,
                        "weight":w,"total":tot,"path":path})

    # ─── 2. Weather-adjusted ──────────────────
    section("2.  Weather-Adjusted Fastest Route")
    w_tot, w_path = g.dijkstra(source, target, "time", weather=True)
    norm = results["time"][0]
    if w_path:
        delay = w_tot - norm
        print(f"\n  Normal fastest time     : {norm:.2f} h")
        print(f"  Weather-adjusted time   : {w_tot:.2f} h  (+{delay:.2f} h)")
        print(f"  Route                   : {' → '.join(w_path)}")
        print(f"\n  Leg-by-leg weather:")
        div()
        for i in range(len(w_path)-1):
            a, b = w_path[i], w_path[i+1]
            cond = g.weather.get_weather(a, b)
            mult = WEATHER_MULT[cond]
            blk  = "  🚧 BLOCKED" if g.roadblocks.blocked(a,b) else ""
            safe = get_safety(a, b)
            print(f"  {WEATHER_ICON[cond]}  {a:<15} → {b:<15} | {cond:<8} ×{mult:.1f}"
                  f"  {safety_label(safe)}{blk}")
        div()
    else:
        print("  ❌ No weather-adjusted path found.")

    # ─── 3. ★ Fuel Cost ───────────────────────
    section(f"3.  ★ Fuel Cost Estimator  [{vehicle}]")
    dist_km = results["distance"][0]
    if dist_km < math.inf:
        fuel_comparison(dist_km)
        selected_cost = fuel_cost(dist_km, vehicle)
        print(f"\n  Your vehicle ({vehicle}): Rs {selected_cost:.2f} for {dist_km:.0f} km")

    # ─── 4. ★ Tourist Attractions on route ───
    section("4.  ★ Tourist Attractions Along Route")
    best_path = results["distance"][1]
    if best_path:
        route_attraction_summary(best_path)
    else:
        print("  No route available to show attractions.")

    # ─── 5. BFS & DFS ─────────────────────────
    section("5.  BFS & DFS Traversal from Source")
    bfs_o = g.bfs(source)
    dfs_o = g.dfs(source)
    print(f"\n  🌐  BFS  ({len(bfs_o)} cities):")
    print(f"      {' → '.join(bfs_o)}")
    print(f"\n  🌲  DFS  ({len(dfs_o)} cities):")
    print(f"      {' → '.join(dfs_o)}")
    bfs_step = bfs_o.index(target)+1 if target in bfs_o else -1
    dfs_step = dfs_o.index(target)+1 if target in dfs_o else -1
    print(f"\n  '{target}' — BFS step {bfs_step},  DFS step {dfs_step}")
    g.push_history({"type":"bfs","source":source,"order":bfs_o})
    g.push_history({"type":"dfs","source":source,"order":dfs_o})

    # ─── 6. All Paths ─────────────────────────
    section("6.  All Possible Paths  (DFS Backtracking)")
    paths = g.all_paths(source, target)
    if not paths:
        print("  ❌ No paths found.")
    else:
        path_data = []
        for p in paths:
            d=c=t=0.0
            for i in range(len(p)-1):
                a,b = p[i], p[i+1]
                edge = next(((dd,cc,tt) for nb,dd,cc,tt in g.adj[a] if nb==b), None)
                if edge: d+=edge[0]; c+=edge[1]; t+=edge[2]
            path_data.append((p,d,c,t))
        path_data.sort(key=lambda x:x[1])
        print(f"\n  Found {len(path_data)} path(s) — sorted by distance:\n")
        print(f"  {'#':<4} {'Distance':>10}  {'Cost':>10}  {'Time':>8}  {'Safety':>12}  Route")
        div()
        for i,(p,d,c,t) in enumerate(path_data,1):
            # Average safety across legs
            safety_scores = [get_safety(p[j],p[j+1]) for j in range(len(p)-1)]
            avg_safe = sum(safety_scores)/len(safety_scores) if safety_scores else 0
            tag = "  ← shortest" if i==1 else ""
            print(f"  {i:<4} {d:>8.1f}km  Rs{c:>8.0f}  {t:>6.2f}h  "
                  f"{avg_safe:>5.1f}/10 ★{tag}")
            print(f"       {' → '.join(p)}")
        div()

    # ─── 7. ★ Safety Report ───────────────────
    section("7.  ★ Route Safety Report")
    opt_path = results["distance"][1]
    if opt_path:
        print(f"\n  Safety check on optimal route  ({' → '.join(opt_path)}):\n")
        overall = []
        for i in range(len(opt_path)-1):
            a,b = opt_path[i], opt_path[i+1]
            s   = get_safety(a,b)
            overall.append(s)
            blk = "  🚧 BLOCKED" if g.roadblocks.blocked(a,b) else ""
            print(f"  {a:<15} → {b:<15}  {safety_label(s)}  ({s}/10){blk}")
        avg = sum(overall)/len(overall)
        div()
        print(f"  Overall Route Safety: {avg:.1f}/10  {safety_label(round(avg))}")

    # ─── 8. Roadblock status ──────────────────
    section("8.  Roadblock Status on Optimal Route")
    if opt_path:
        blocked_count = 0
        for i in range(len(opt_path)-1):
            a,b = opt_path[i], opt_path[i+1]
            if g.roadblocks.blocked(a,b):
                blocked_count += 1
                print(f"  🚧  {a} → {b}  BLOCKED  [{g.roadblocks.reason(a,b)}]")
            else:
                print(f"  ✅  {a} → {b}  Clear")
        print()
        if blocked_count:
            print(f"  ⚠️   {blocked_count} roadblock(s) — Dijkstra auto-rerouted.")
        else:
            print(f"  All {len(opt_path)-1} leg(s) clear. Safe travels!")

    # ─── 9. ★ Best Season ─────────────────────
    section("9.  ★ Best Season to Travel")
    for city in [source, target]:
        season = BEST_SEASON.get(city, "Year-round (verify locally)")
        print(f"  📅  {city:<15} : {season}")
    if best_path and len(best_path) > 2:
        print(f"\n  Intermediate cities on route:")
        for city in best_path[1:-1]:
            season = BEST_SEASON.get(city, "Year-round")
            print(f"  📅  {city:<15} : {season}")

    # ─── 10. Route Comparison ─────────────────
    section("10. Route Metric Comparison")
    print(f"\n  {'Metric':<12} {'Best Value':>13}  Route")
    div()
    for w in ["distance","cost","time"]:
        tot, path = results[w]
        u  = UNITS[w]; ic = ICONS[w]
        if path:
            print(f"  {ic} {w.capitalize():<10} {tot:>10.2f} {u:<4}  {' → '.join(path)}")
        else:
            print(f"  {ic} {w.capitalize():<10} {'N/A':>10}       No route")
    div()

    # ─── 11. ★ Trip Summary Report ────────────
    section("11. ★ Complete Trip Summary")
    d_tot, d_path = results["distance"]
    c_tot, _      = results["cost"]
    t_tot, _      = results["time"]
    attractions   = attractions_on_route(d_path or [])
    total_attr_time = sum(s[1] for spots in attractions.values() for s in spots)
    total_attr_cost = sum(s[2] for spots in attractions.values() for s in spots)
    f_cost = fuel_cost(d_tot if d_tot < math.inf else 0, vehicle)

    print(f"""
  ┌─────────────────────────────────────────────────────┐
  │  TRIP: {source:<20} →  {target:<17}│
  ├─────────────────────────────────────────────────────┤
  │  🛣️   Distance          : {d_tot:>8.1f} km              │
  │  💰  Road/Train Cost    : Rs {c_tot:>8.1f}              │
  │  ⏱️   Travel Time        : {t_tot:>8.2f} h               │
  │  ⛽  Fuel ({vehicle:<7})     : Rs {f_cost:>8.2f}              │
  │  🏛️   Attraction Time    : {total_attr_time:>8.1f} h               │
  │  🎟️   Attraction Cost    : Rs {total_attr_cost:>8.1f}              │
  ├─────────────────────────────────────────────────────┤
  │  💵  ESTIMATED TOTAL    : Rs {c_tot+f_cost+total_attr_cost:>8.1f}              │
  │  🕐  TOTAL TRIP TIME    : {t_tot+total_attr_time:>8.1f} h               │
  └─────────────────────────────────────────────────────┘""")

    # ─── 12. Stack History ────────────────────
    section("12. Route History  (Stack — newest first)")
    hist = g.history._d
    print(f"\n  Stack size: {len(hist)}\n")
    for i, e in enumerate(reversed(hist[-8:]), 1):
        tag = e["type"].upper()
        if tag == "DIJKSTRA":
            print(f"  {i:>2}. [{tag:<8}] {e['source']} → {e['target']}"
                  f"  by {e['weight']:<10} = {e['total']:.2f} {UNITS.get(e['weight'],'')}")
        else:
            o = e["order"]
            print(f"  {i:>2}. [{tag:<8}] from {e['source']}: "
                  f"{' → '.join(o[:5])}{'...' if len(o)>5 else ''}")
    print(f"\n  Tip: option 5 in menu pops (undoes) the top entry.")

    # ─── 13. Time Complexity ──────────────────
    section("13. Time Complexity Reference")
    tbl = [
        ("Dijkstra",           "O((V+E) log V)",  "Min-heap PQ, V=cities"),
        ("BFS",                "O(V + E)",         "Queue-based"),
        ("DFS",                "O(V + E)",         "Recursive"),
        ("All Paths (DFS)",    "O(V!)",            "Exponential worst case"),
        ("Add Route",          "O(1)",             "Adjacency list append"),
        ("Stack push/pop",     "O(1)",             "Array-backed"),
        ("Queue enq/deq",      "O(1)",             "Deque-backed"),
        ("Roadblock check",    "O(1)",             "Hash set"),
        ("Weather lookup",     "O(1)",             "Hash map"),
        ("Fuel estimate",      "O(1)",             "Arithmetic formula"),
        ("Safety lookup",      "O(1)",             "Dict lookup"),
        ("Nearest city",       "O(V × Dijkstra)", "Run Dijkstra V times"),
    ]
    print(f"\n  {'Operation':<24} {'Complexity':<20} Notes")
    div()
    for nm, tc, note in tbl:
        print(f"  {nm:<24} {tc:<20} {note}")
    div()

    banner(f"ANALYSIS COMPLETE  :  {source}  →  {target}")


# ════════════════════════════════════════════════════════════════
#  GRAPH BUILDER
# ════════════════════════════════════════════════════════════════
def build_graph() -> TravelGraph:
    g = TravelGraph()
    routes = [
        ("Delhi",     "Jaipur",    281,   450,  4.5),
        ("Delhi",     "Mumbai",   1400,  1800, 18.0),
        ("Delhi",     "Kolkata",  1472,  1900, 20.0),
        ("Mumbai",    "Pune",      148,   250,  2.5),
        ("Mumbai",    "Bangalore", 981,  1200, 12.0),
        ("Mumbai",    "Hyderabad", 711,   900,  9.5),
        ("Bangalore", "Chennai",   347,   500,  5.0),
        ("Bangalore", "Hyderabad", 575,   750,  7.5),
        ("Chennai",   "Hyderabad", 627,   800,  8.5),
        ("Hyderabad", "Kolkata",  1501,  1700, 19.0),
        ("Pune",      "Hyderabad", 559,   700,  7.0),
        ("Jaipur",    "Mumbai",   1150,  1500, 15.0),
    ]
    for r in routes:
        g.add_route(*r)

    g.weather.set_weather("Delhi",   "Mumbai",    "Rainy")
    g.weather.set_weather("Mumbai",  "Bangalore", "Clear")
    g.weather.set_weather("Delhi",   "Kolkata",   "Foggy")
    g.weather.set_weather("Chennai", "Hyderabad", "Stormy")
    g.weather.set_weather("Delhi",   "Jaipur",    "Snowy")
    g.weather.set_weather("Jaipur",  "Mumbai",    "Cloudy")

    g.roadblocks.add("Chennai", "Hyderabad", "Cyclone warning")
    return g


# ════════════════════════════════════════════════════════════════
#  MENU HELPERS
# ════════════════════════════════════════════════════════════════
def city_list(g):
    cities = sorted(g.cities)
    print("\n  Available cities:")
    for i,c in enumerate(cities,1):
        print(f"    {i:>2}. {c}")
    return cities

def pick_city(prompt, cities) -> str | None:
    raw = input(prompt).strip()
    for c in cities:
        if c.lower() == raw.lower(): return c
    if raw.isdigit():
        idx = int(raw)-1
        if 0 <= idx < len(cities): return cities[idx]
    print(f"  '{raw}' not found.")
    return None

def pick_vehicle() -> str:
    print("\n  Select vehicle type:")
    opts = list(FUEL_RATES.keys())
    for i,v in enumerate(opts,1): print(f"    {i}. {v}")
    raw = input("  Choice [1]: ").strip()
    if raw.isdigit():
        idx = int(raw)-1
        if 0 <= idx < len(opts): return opts[idx]
    return "Petrol"

def show_network(g):
    print("\n" + "=" * W)
    print("  FULL TRAVEL NETWORK")
    print("=" * W)
    for city in sorted(g.adj):
        print(f"\n  {city}  (Best time: {BEST_SEASON.get(city,'—')})")
        for nb, dist, cost, time in g.adj[city]:
            blk  = "  🚧 BLOCKED" if g.roadblocks.blocked(city,nb) else ""
            cond = g.weather.get_weather(city,nb)
            safe = get_safety(city,nb)
            print(f"    → {nb:<18} {dist:>7.0f}km  Rs{cost:>7.0f}  "
                  f"{time:>5.1f}h  {WEATHER_ICON[cond]}{cond:<8} "
                  f"{safety_label(safe)}{blk}")
    print()

def manage_roadblocks(g, cities):
    print("\n  Roadblock Manager")
    print("  1. Add    2. Remove    3. View all")
    ch = input("  Choice: ").strip()
    if ch == "1":
        city_list(g)
        a = None
        while a is None: a = pick_city("  Source: ", cities)
        b = None
        while b is None: b = pick_city("  Dest  : ", cities)
        reason = input("  Reason (Enter=skip): ").strip() or "Under maintenance"
        g.roadblocks.add(a,b,reason)
        print(f"  🚧 Roadblock added: {a} ↔ {b}")
    elif ch == "2":
        bls = g.roadblocks.all()
        if not bls: print("  No active roadblocks."); return
        for i,k in enumerate(bls,1):
            print(f"    {i}. {k[0]} ↔ {k[1]}  [{g.roadblocks.reason(*k)}]")
        sel = input("  Remove number: ").strip()
        if sel.isdigit():
            idx = int(sel)-1
            if 0 <= idx < len(bls):
                g.roadblocks.remove(*bls[idx])
                print(f"  ✅ Cleared: {bls[idx][0]} ↔ {bls[idx][1]}")
    elif ch == "3":
        bls = g.roadblocks.all()
        if not bls: print("  No active roadblocks.")
        else:
            for k in bls:
                print(f"  🚧 {k[0]} ↔ {k[1]}  [{g.roadblocks.reason(*k)}]")

def show_weather_report(g):
    print("\n" + "-"*55)
    print("  WEATHER REPORT — ALL ROUTES")
    print("-"*55)
    for a,b in g.get_all_edges():
        cond = g.weather.get_weather(a,b)
        print(f"  {WEATHER_ICON[cond]}  {a:<15} ↔  {b:<15} | {cond:<8}  {WEATHER_ADV[cond]}")
    print("-"*55)

def show_attractions_menu(g, cities):
    print("\n  Attraction Explorer")
    print("  1. Explore one city's attractions")
    print("  2. Set budget filter")
    ch = input("  Choice: ").strip()
    city = None
    while city is None:
        city_list(g)
        city = pick_city("  Select city: ", cities)
    budget = None
    if ch == "2":
        raw = input("  Max entry cost per attraction (Rs): ").strip()
        if raw.isdigit(): budget = float(raw)
    display_attractions(city, budget)

def show_nearest(g, cities):
    city = None
    while city is None:
        city_list(g)
        city = pick_city("  Select your city: ", cities)
    n_raw = input("  How many nearest cities to show? [3]: ").strip()
    n = int(n_raw) if n_raw.isdigit() else 3
    nearest = g.nearest_cities(city, n)
    print(f"\n  🗺️   {n} Nearest Cities from {city}:")
    div()
    for dist, c in nearest:
        print(f"  {c:<18} {dist:.0f} km")
    div()

def multi_stop_menu(g, cities):
    print("\n  Multi-Stop Route Planner")
    print("  Enter cities one by one. Empty line = done.\n")
    waypoints = []
    city_list(g)
    while True:
        raw = input(f"  Waypoint {len(waypoints)+1} (Enter to finish): ").strip()
        if not raw: break
        c = pick_city("  > ", cities) if not raw.isdigit() else None
        if raw.isdigit():
            idx = int(raw)-1
            if 0 <= idx < len(cities): c = cities[idx]
        if c: waypoints.append(c)
    if len(waypoints) < 2:
        print("  Need at least 2 cities."); return
    print(f"\n  Route: {' → '.join(waypoints)}")
    w = input("  Optimise by [distance/cost/time]: ").strip() or "distance"
    if w not in ("distance","cost","time"): w = "distance"
    total, path = g.multi_stop_route(waypoints, w)
    if not path:
        print("  ❌ No valid multi-stop route found.")
    else:
        print(f"\n  ✅ Multi-Stop Route ({w}):")
        print(f"     Total  : {total:.2f}")
        print(f"     Path   : {' → '.join(path)}")
        print(f"\n  Attractions along the way:")
        route_attraction_summary(path)


# ════════════════════════════════════════════════════════════════
#  MAIN
# ════════════════════════════════════════════════════════════════
def main():
    banner("GRAPH-BASED TRAVEL PLANNER  v3.0  —  DSA PROJECT")
    g = build_graph()
    cities = sorted(g.cities)
    vehicle = "Petrol"

    print(f"\n  Network: {len(g.cities)} cities | {len(g.get_all_edges())} routes | "
          f"{len(g.roadblocks.all())} roadblock(s) | Vehicle: {vehicle}")

    while True:
        print("\n" + "─" * W)
        print("  MAIN MENU")
        print("  1.  🔍  Plan a trip  (full analysis)")
        print("  2.  🗺️   View full network")
        print("  3.  🚧  Manage roadblocks")
        print("  4.  🕒  View route history  (Stack)")
        print("  5.  ↩️   Undo last action  (Stack pop)")
        print("  6.  🌦️   Weather report")
        print("  7.  🏛️   Explore attractions in a city")
        print("  8.  📍  Find nearest cities")
        print("  9.  🛤️   Multi-stop route planner")
        print(" 10.  ⛽  Change vehicle type  (current: " + vehicle + ")")
        print("  0.  ❌  Exit")
        print("─" * W)
        ch = input("  Choice: ").strip()

        if ch == "1":
            cities = sorted(g.cities)
            city_list(g); print()
            src = None
            while src is None:
                src = pick_city("  SOURCE (name or #): ", cities)
            dst = None
            while dst is None:
                dst = pick_city("  DEST   (name or #): ", cities)
            if src == dst:
                print("  Same city entered for source and destination!")
            else:
                full_analysis(g, src, dst, vehicle)

        elif ch == "2":   show_network(g)
        elif ch == "3":   manage_roadblocks(g, sorted(g.cities))
        elif ch == "4":
            hist = g.history._d
            UNITS = {"distance":"km","cost":"Rs","time":"h"}
            if not hist: print("  No history yet.")
            else:
                print(f"\n  History ({len(hist)} entries, newest first):\n")
                for i,e in enumerate(reversed(hist),1):
                    tag = e["type"].upper()
                    if tag == "DIJKSTRA":
                        u = UNITS.get(e["weight"],"")
                        print(f"  {i:>2}. [{tag}] {e['source']} → {e['target']}"
                              f"  by {e['weight']} = {e['total']:.2f} {u}")
                    else:
                        o = e["order"]
                        print(f"  {i:>2}. [{tag}] from {e['source']}: "
                              f"{' → '.join(o[:5])}{'...' if len(o)>5 else ''}")

        elif ch == "5":
            p = g.undo_last()
            if p:
                tag = p["type"].upper()
                if tag == "DIJKSTRA":
                    print(f"  ↩️  Undone: {p['source']} → {p['target']} by {p['weight']}")
                else:
                    print(f"  ↩️  Undone: {tag} from {p['source']}")

        elif ch == "6":   show_weather_report(g)
        elif ch == "7":   show_attractions_menu(g, sorted(g.cities))
        elif ch == "8":   show_nearest(g, sorted(g.cities))
        elif ch == "9":   multi_stop_menu(g, sorted(g.cities))
        elif ch == "10":
            vehicle = pick_vehicle()
            print(f"  Vehicle set to: {vehicle}")
        elif ch == "0":
            print("\n  Goodbye! Safe travels. 🙏\n")
            break
        else:
            print("  Invalid choice.")


if __name__ == "__main__":
    main()